#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Application;
use NMarniesse\Phindexer\Test\Performance\Command;

set_time_limit(0);

require __DIR__.'/../../vendor/autoload.php';

$application = new Application();

$application->add(new Command\PerformanceCheckForArray());

$application->run();
